//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TgSupportBot {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TgSupportBot.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to изображения.
        /// </summary>
        internal static string ImageFew {
            get {
                return ResourceManager.GetString("ImageFew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to изображений.
        /// </summary>
        internal static string ImageMany {
            get {
                return ResourceManager.GetString("ImageMany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to изображение.
        /// </summary>
        internal static string ImageOne {
            get {
                return ResourceManager.GetString("ImageOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваше сообщение превышает допустимую длинну в {0} символов.
        /// </summary>
        internal static string MessageMaxLimitMessage_1 {
            get {
                return ResourceManager.GetString("MessageMaxLimitMessage_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы сможете прикрепить фото или видео позже, вам нужно ввести только текст 🤗.
        /// </summary>
        internal static string MessageOnlyTextLimit {
            get {
                return ResourceManager.GetString("MessageOnlyTextLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы предоставили {0} {1} и {2} видео, вы можете добавить ещё или завершить создание заявки нажав на соответствующую кнопку снизу.
        /// </summary>
        internal static string PresentedMediaMessage_3 {
            get {
                return ResourceManager.GetString("PresentedMediaMessage_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить создание заявки.
        /// </summary>
        internal static string ReportCancelButton {
            get {
                return ResourceManager.GetString("ReportCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Создать заявку.
        /// </summary>
        internal static string ReportCommandDescription {
            get {
                return ResourceManager.GetString("ReportCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завершить создание заявки.
        /// </summary>
        internal static string ReportCreateButton {
            get {
                return ResourceManager.GetString("ReportCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не предоставлять изображения.
        /// </summary>
        internal static string ReportSkipAttachments {
            get {
                return ResourceManager.GetString("ReportSkipAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не предоставлять описание.
        /// </summary>
        internal static string ReportSkipDescription {
            get {
                return ResourceManager.GetString("ReportSkipDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не предоставлять место.
        /// </summary>
        internal static string ReportSkipLocation {
            get {
                return ResourceManager.GetString("ReportSkipLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос: {0}
        ///Создан: @{1}
        ///Описание: {2}
        ///Местоположение: {3}.
        /// </summary>
        internal static string RequestMessage_4 {
            get {
                return ResourceManager.GetString("RequestMessage_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете прислать изображения или видео, чтобы прикрепить их к заявке.
        /// </summary>
        internal static string RequireAttachmentMessage {
            get {
                return ResourceManager.GetString("RequireAttachmentMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предоставьте краткое описание заявки.
        /// </summary>
        internal static string RequireBriefMessage {
            get {
                return ResourceManager.GetString("RequireBriefMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предоставьте подробное описание проблемы.
        /// </summary>
        internal static string RequireDescriptionMessage {
            get {
                return ResourceManager.GetString("RequireDescriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предоставьте номер вашего кабинета и литеру здания:.
        /// </summary>
        internal static string RequireLocationMessage {
            get {
                return ResourceManager.GetString("RequireLocationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Приветствуем вас @{0}.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⚠ ВНИМАНИЕ ⚠
        ///В текущее время услуги технической поддержики не предоставляются!
        ///
        ///Ваша заявка будет рассмотрена позже!
        ///
        ///Активные часы работы тех. поддержки от 9:00 до 18:00.
        /// </summary>
        internal static string WorkTimeWarningMessage {
            get {
                return ResourceManager.GetString("WorkTimeWarningMessage", resourceCulture);
            }
        }
    }
}
