name: Build

on:
  release:
    types: [created]

jobs:
  build:
    permissions: write-all
    strategy:
      matrix:
        os: [linux-x64, linux-arm64, win-x64, win-arm64]
        framework: [net5.0, net9.0]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Build
      run: dotnet publish ./TgSupportBot.csproj -c Release -r ${{ matrix.os }} --framework ${{ matrix.framework }} --self-contained true -p:PublishTrimmed=true -p:PublishSingleFile=true -o ./build/${{ matrix.framework }}/${{ matrix.os }}/

    - name: Zip Builds
      run: |
        cd ./build/${{ matrix.framework }}/${{ matrix.os }}
        zip -r ../${{ matrix.os }}-${{ matrix.framework }}.zip ./
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./build/*.zip
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
